/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
 * Generated on: 05-May-2013 10:07:51
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2013a\extern\include\tmwtypes.h 
 */
#define lp_MWSPT_NSEC 11
const int lp_NL[lp_MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,2,1 };
const double lp_NUM[lp_MWSPT_NSEC][3] = {
  {
     0.8881378607931,                 0,                 0 
  },
  {
                   1,    1.917798262869,                 1 
  },
  {
     0.7868345789816,                 0,                 0 
  },
  {
                   1,    1.936134371933,                 1 
  },
  {
     0.7186918708018,                 0,                 0 
  },
  {
                   1,    1.964562241675,                 1 
  },
  {
     0.6794456372162,                 0,                 0 
  },
  {
                   1,    1.989902782966,                 1 
  },
  {
     0.8164709349001,                 0,                 0 
  },
  {
                   1,                 1,                 0 
  },
  {
                   1,                 0,                 0 
  }
};
const int lp_DL[lp_MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,2,1 };
const double lp_DEN[lp_MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.615362804256,   0.8641821639474 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.445173372529,   0.6519132588255 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.339930871696,   0.5093677826838 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.283542639018,   0.4273793997842 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   0.6329418698001,                 0 
  },
  {
                   1,                 0,                 0 
  }
};
